### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by easyhooon** [KU-LAST/psychat-android#1]
- [x] 프로젝트 세팅
- [x] 네트워크 통신 환경 세팅
- [x] 화면 구성
---
- [x] 채팅 기능 구현 방법 조사
- [ ] AI 모델을 앱에 연동하는 방법 조사
